/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "surface-container-lowest": "#060f17",
              "inverse-on-surface": "#28313b",
              "on-secondary-container": "#d4a5ff",
              "on-primary-container": "#005763",
              "primary-fixed": "#a2eeff",
              "tertiary-container": "#b9c0da",
              "primary-container": "#22d3ee",
              "tertiary-fixed": "#dae2fd",
              "secondary": "#deb7ff",
              "on-tertiary-container": "#474e64",
              "on-primary-fixed": "#001f25",
              "surface-bright": "#313a44",
              "inverse-surface": "#dae3f0",
              "secondary-container": "#603389",
              "on-tertiary-fixed-variant": "#3f465c",
              "outline-variant": "#3c494c",
              "on-tertiary": "#283044",
              "error": "#ffb4ab",
              "on-surface": "#dae3f0",
              "surface-tint": "#2fd9f4",
              "surface-container": "#172129",
              "surface-container-highest": "#2c363f",
              "on-secondary-fixed-variant": "#5d3186",
              "outline": "#859397",
              "tertiary-fixed-dim": "#bec6e0",
              "on-primary": "#00363e",
              "background": "#0a141d",
              "surface-dim": "#0a141d",
              "surface-container-low": "#131d25",
              "primary-fixed-dim": "#2fd9f4",
              "secondary-fixed": "#f1dbff",
              "on-secondary": "#45166e",
              "surface-container-high": "#212b34",
              "on-primary-fixed-variant": "#004e5a",
              "on-error": "#690005",
              "tertiary": "#d5dcf6",
              "error-container": "#93000a",
              "on-secondary-fixed": "#2d0050",
              "secondary-fixed-dim": "#deb7ff",
              "surface-variant": "#2c363f",
              "on-error-container": "#ffdad6",
              "inverse-primary": "#006877",
              "on-surface-variant": "#bbc9cd",
              "on-tertiary-fixed": "#131b2e",
              "on-background": "#dae3f0",
              "primary": "#8aebff",
              "surface": "#0a141d"
      },
      "borderRadius": {
              "DEFAULT": "1rem",
              "lg": "2rem",
              "xl": "3rem",
              "full": "9999px"
      },
      "spacing": {
              "unit": "8px",
              "stack-lg": "32px",
              "gutter": "24px",
              "container-max": "1280px",
              "stack-sm": "8px",
              "margin-page": "40px",
              "stack-md": "16px"
      },
      "fontFamily": {
              "body-lg": ["Lexend", "sans-serif"],
              "body-sm": ["Lexend", "sans-serif"],
              "h3": ["Space Grotesk", "sans-serif"],
              "label-caps": ["Space Grotesk", "sans-serif"],
              "body-md": ["Lexend", "sans-serif"],
              "h1": ["Space Grotesk", "sans-serif"],
              "h2": ["Space Grotesk", "sans-serif"]
      },
      "fontSize": {
              "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
              "h3": ["24px", {"lineHeight": "1.3", "letterSpacing": "0em", "fontWeight": "600"}],
              "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700"}],
              "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "h1": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "h2": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
